### ISSUE TITLE
Interesse über Deine Lösung zu schreiben? 

### ISSUE THREAD

**Issue by svenruppert** [moewes/quarkus-vaadin-lab#14]
Hallo Maik,
in den Log Meldungen im git habe ich deutsche Kommentare gefunden. Deswegen schreibe ich Dich einfach einmal so an.
Deine Lösung sieht gut aus und ich würde das gerne als Tutorial mit auf die Vaadin Webseite nehmen.
Hast Du Interesse das mit mir zusammen im Co Authorship zu machen?

meine email ist sven . ruppert (a) gmail

Cheers Sven

**Comment by Xenon2k7** [comment]
> Hallo Maik,
> in den Log Meldungen im git habe ich deutsche Kommentare gefunden. Deswegen schreibe ich Dich einfach einmal so an.
> Deine Lösung sieht gut aus und ich würde das gerne als Tutorial mit auf die Vaadin Webseite nehmen.
> Hast Du Interesse das mit mir zusammen im Co Authorship zu machen?
> 
> meine email ist sven . ruppert (a) gmail
> 
> Cheers Sven

Würde ich auch zu gern live sehen, das Framework ist super, aber auf den Tomcat Start 40 Sekunden langweilt. Daher fände ich eine Quarkus Lösung top!

**Comment by svenruppert** [comment]
ok, Rest auf anderem Kanal.
