### ISSUE TITLE
Changing anything in the Java Frontend breaks the app

### ISSUE THREAD

**Issue by Xenon2k7** [moewes/quarkus-vaadin-lab#15]
Sobald man eine Änderung im dev mode an einem component macht und refreshed, bekomme ich folgenden Fehler und bekomme die Seite nicht mehr zum Laufen, außer ich baue die Anwendung neu:
![image](https://user-images.githubusercontent.com/7736307/66395133-fe494a80-e9d6-11e9-949c-9a372c04385d.png)

Der Test war in der AccordionView ein neues Panel einzufügen:
"accordion.add("Panel 4", new Span("Panel content"))
    .addThemeVariants(DetailsVariant.FILLED);"

Jeder weitere Refresh auf die Seite löst ein recompiling aus, da angeblich Änderungen entdeckt worden sind:
"2019-10-08 14:22:46,806 INFO  [io.qua.dev] (vert.x-worker-thread-13) Changed source files detected, recompiling [C:\Users\julian.mueller\git\quarkus-vaadin-lab\example\src\main\java\net\moewes\cloud\ui\applayout\AccordionView.java]"

GraalVM Native Mode noch nicht getestet, probiere ich aber gern noch aus. Würde Vaadin super gern mit GraalVM nutzen, für private Anwendungen im eigenen Homenetz. Erstmal Danke für die Umsetzung!

**Comment by moewes** [comment]
Hallo Julian,
wenn Du im quarkus:dev mode bist, führt jede Änderung am Quellcode zu einer Neucompilierung der entsprechenden Java-Datei. Dabei scheint es bei Dir auf dem System zu einem Problem beim Laden einer Jar-Datei im Classpath zu kommen. Jedes weitere Refresh führt dabei zwangsläufig zu einem weiteren Compilierungsversuch, da dieser ja vorher nicht erfolgreich war. Augenscheinlich scheint mir das Problem aber gar nichts mit der Extension oder mit Vaadin zu tun zu haben.
Es scheint der Pfad zu Deinem Maven-Repository nicht korrekt angegeben zu sein.
Hast Du einmal versucht das Getting Started Tutorial von Quarkus auszuführen und im dev-mode Änderungen zu machen? Führt das zum gleichen Fehler?
Du könntest auch versuchen das Ganze in einem Container laufen zu lassen. GraalVM und Windows scheint ohnehin aktuell noch nicht ganz sicher zu laufen. Ich selber arbeite/teste unter Unix  (macos).
Viele Grüße
Maik

**Comment by Xenon2k7** [comment]
Hallo Maik, danke für die Antwort. Ich denke auch es liegt an der bis jetzt nur simplen Umsetzung der GraalVM für Windows. Mach den Issue hier sonst zu, möchte dein Projekt damit nicht belasten. Werde mir mal ein Linux für diese Zwecke aufsetzen demnächst. Ansonsten super Arbeit!
Gruß Julian
